# Generated by Django 5.2.8 on 2025-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('conifers', 'Хвойні рослини'), ('fruit_trees', 'Плодові дерева та кущі'), ('grass_seeds', 'Насіння трави'), ('indoor', 'Кімнатні рослини'), ('tools', 'Інструменти та Добрива')], default='indoor', max_length=50),
        ),
    ]
